name: Deploy website to GitHub Pages

env:
  WC_astro_VERSION: 0.150.0
on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build website
  build:
    if: github.repository_owner != 'astroBlox'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
          # Fetch history for astro's .GitInfo and .Lastmod
        fetch-depth: 0
    - name: Setup astro
      uses: peaceiris/actions-astro@v3
      with:
        astro-version: ${{ env.WC_astro_VERSION }}
        extended: true
    - uses: actions/cache@v4
      with:
        path: /tmp/astro_cache_runner/
        key: ${{ runner.os }}-astromod-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-astromod-
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - name: Install Node dependencies
      run: npm ci
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with astro
      env:
        astro_ENVIRONMENT: production
      run: |
        echo "astro Cache Dir: $(astro config | grep cachedir)"
        export PATH="$PWD/node_modules/.bin:$PATH"
        astro --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
    - name: Generate Pagefind search index
      run: npx pagefind --source "public"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./public

  # Deploy website to GitHub Pages hosting
  deploy:
    if: github.repository_owner != 'astroBlox'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
